version: "3.9"

services:
  postgres:
    image: postgres:15
    restart: always
    container_name: agil-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agil_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
